<a href="https://colab.research.google.com/github/programmerasdas-design/Bookstore-Sales-Analysis/blob/main/Restaurant_Orders_Dirty_1000.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [330]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data=pd.read_csv("/content/Restaurant_Orders_Dirty_1000.csv")
data.head()

,Order_ID,Customer_Name,Restaurant,City,Food_Item,Category,Quantity,Price,Delivery_Time_Minutes,Rating,Payment_Method,Order_Date
0,137,Sara,Kcf,Asyut,Pasta,Italian,3,129.0,47,1.0,Cash,2025-04-03
1,629,Mostafa,KFC,Cario,Pasta,Italian,2,663.0,31,5.0,Crad,09-29-2025
2,185,Mahmoud,Hardee's,GIZA,Pasta,Healthy,6,541.0,54,5.0,card,26/04/2025
3,32,Hassan,PizzaHot,GIZA,Salad,Fast Food,2,127.0,-30,5.0,Cash,03-24-2025
4,678,Omar,BurgerKing,cairo,Fries,Italian,2,474.0,57,2.0,Wallet,10/03/2025

In [331]:
data.tail()

,Order_ID,Customer_Name,Restaurant,City,Food_Item,Category,Quantity,Price,Delivery_Time_Minutes,Rating,Payment_Method,Order_Date
1035,88,Sara,KFC,Cairo,Pizza,Healthy,1,197.0,62,2.0,cash,09-15-2025
1036,331,Nour,KFC,giza,Burger,Italian,6,550.0,86,4.0,CASH,08-26-2025
1037,467,Hassan,Kcf,Cario,Fries,Healthy,4,NaN,33,5.0,Crad,2025-05-09
1038,122,Nour,BurgerKing,Cairo,Burger,Italian,5,266.0,27,3.0,card,2025-01-24
1039,861,Omar,Mc Donalds,Asyut,Burger,Fast Food,4,456.0,72,3.0,CASH,31/10/2025

In [332]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1040 entries, 0 to 1039
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Order_ID               1040 non-null   int64
 1   Customer_Name          1040 non-null   object
 2   Restaurant             1010 non-null   object
 3   City                   1009 non-null   object
 4   Food_Item              1040 non-null   object
 5   Category               1040 non-null   object
 6   Quantity               1040 non-null   int64
 7   Price                  1010 non-null   float64
 8   Delivery_Time_Minutes  1040 non-null   int64
 9   Rating                 1010 non-null   float64
 10  Payment_Method         1010 non-null   object
 11  Order_Date             1040 non-null   object
dtypes: float64(2), int64(3), object(7)
memory usage: 97.6+ KB

In [333]:
data.shape

(1040, 12)

In [334]:
data.describe()

,Order_ID,Quantity,Price,Delivery_Time_Minutes,Rating
count,1040.000000,1040.000000,1010.000000,1040.000000,1010.000000
mean,502.310577,5.468269,572.340594,54.002885,3.004950
std,288.812178,2.990030,1661.856618,50.330907,1.413854
min,1.000000,-2.000000,-200.000000,-30.000000,1.000000
25%,251.750000,3.000000,203.500000,29.000000,2.000000
50%,504.500000,5.000000,376.500000,48.000000,3.000000
75%,751.250000,8.000000,535.000000,70.000000,4.000000
max,1000.000000,10.000000,13571.000000,366.000000,5.000000

In [335]:
data.columns

Index(['Order_ID', 'Customer_Name', 'Restaurant', 'City', 'Food_Item',
       'Category', 'Quantity', 'Price', 'Delivery_Time_Minutes', 'Rating',
       'Payment_Method', 'Order_Date'],
      dtype='object')

In [336]:
data.dtypes

Order_ID                   int64
Customer_Name             object
Restaurant                object
City                      object
Food_Item                 object
Category                  object
Quantity                   int64
Price                    float64
Delivery_Time_Minutes      int64
Rating                   float64
Payment_Method            object
Order_Date                object
dtype: object

In [337]:
data.isnull()

,Order_ID,Customer_Name,Restaurant,City,Food_Item,Category,Quantity,Price,Delivery_Time_Minutes,Rating,Payment_Method,Order_Date
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1035,False,False,False,False,False,False,False,False,False,False,False,False
1036,False,False,False,False,False,False,False,False,False,False,False,False
1037,False,False,False,False,False,False,False,True,False,False,False,False
1038,False,False,False,False,False,False,False,False,False,False,False,False
1039,False,False,False,False,False,False,False,False,False,False,False,False

In [338]:
data.isnull().sum()

Order_ID                  0
Customer_Name             0
Restaurant               30
City                     31
Food_Item                 0
Category                  0
Quantity                  0
Price                    30
Delivery_Time_Minutes     0
Rating                   30
Payment_Method           30
Order_Date                0
dtype: int64

In [339]:
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1035    False
1036    False
1037    False
1038    False
1039    False
Length: 1040, dtype: bool

In [340]:
data.duplicated().sum()

np.int64(40)

In [341]:
data.loc[data["Delivery_Time_Minutes"]<=0,"Delivery_Time_Minutes"]=None
data["Delivery_Time_Minutes"]=data["Delivery_Time_Minutes"].fillna(data["Delivery_Time_Minutes"].median())

In [342]:
data.loc[data["Quantity"]<=0,"Quantity"]=None
data["Quantity"]=data["Quantity"].fillna(data["Quantity"].mode()[0])

In [343]:
data["Quantity"]

0       3.0
1       2.0
2       6.0
3       2.0
4       2.0
       ...
1035    1.0
1036    6.0
1037    4.0
1038    5.0
1039    4.0
Name: Quantity, Length: 1040, dtype: float64

In [344]:
data["Rating"]=data["Rating"].fillna(data["Rating"].median())

In [345]:
data["Price"]=data["Price"].fillna(data["Price"].median())

In [346]:
data["Restaurant"]=data["Restaurant"].str.strip()

In [347]:
data["Restaurant"].unique()

array(['Kcf', 'KFC', "Hardee's", 'PizzaHot', 'BurgerKing', 'Mc Donalds',
       'Pizza Hut', "McDonald's", 'Burger King', 'macdonald', nan],
      dtype=object)

In [348]:
data["Restaurant"]=data["Restaurant"].fillna("Unknown")

In [349]:
data["Restaurant"].unique()

array(['Kcf', 'KFC', "Hardee's", 'PizzaHot', 'BurgerKing', 'Mc Donalds',
       'Pizza Hut', "McDonald's", 'Burger King', 'macdonald', 'Unknown'],
      dtype=object)

In [350]:
data["Restaurant"]=data["Restaurant"].replace("Macdonald","Mcdonald'S")

In [351]:
data["Restaurant"]=data["Restaurant"].str.replace(" ","")

In [352]:
data["Restaurant"].unique()

array(['Kcf', 'KFC', "Hardee's", 'PizzaHot', 'BurgerKing', 'McDonalds',
       'PizzaHut', "McDonald's", 'macdonald', 'Unknown'], dtype=object)

In [353]:
data["Restaurant"]=data["Restaurant"].replace("McDonalds","McDonald's")
data["Restaurant"]=data["Restaurant"].replace("macdonald","McDonald's")
data["Restaurant"]=data["Restaurant"].replace("PizzaHut","PizzaHot")
data["Restaurant"]=data["Restaurant"].replace("Kcf","KFC")

In [354]:
data["Restaurant"].unique()

array(['KFC', "Hardee's", 'PizzaHot', 'BurgerKing', "McDonald's",
       'Unknown'], dtype=object)

In [355]:
data["City"].unique()

array(['Asyut', 'Cario', 'GIZA', 'cairo', 'Giza', 'Mansoura', 'Alex',
       'Alexandria', 'CAIRO', 'Cairo', ' Cairo ', nan, 'giza'],
      dtype=object)

In [356]:
data["City"]=data["City"].str.title()
data["City"]=data["City"].str.strip()

In [357]:
data["City"].unique()

array(['Asyut', 'Cario', 'Giza', 'Cairo', 'Mansoura', 'Alex',
       'Alexandria', nan], dtype=object)

In [358]:
data["City"]=data["City"].replace("Alex","Alexandria")
data["City"]=data["City"].replace("Cario","Cairo")

In [359]:
data["City"].unique()

array(['Asyut', 'Cairo', 'Giza', 'Mansoura', 'Alexandria', nan],
      dtype=object)

In [360]:
data["City"]=data["City"].fillna("Unknown")

In [361]:
data["City"].unique()

array(['Asyut', 'Cairo', 'Giza', 'Mansoura', 'Alexandria', 'Unknown'],
      dtype=object)

In [362]:
data.loc[data["Food_Item"]=="Salad","Category"]="Healthy"

In [363]:
data["Category"]

0         Italian
1         Italian
2         Healthy
3         Healthy
4         Italian
          ...
1035      Healthy
1036      Italian
1037      Healthy
1038      Italian
1039    Fast Food
Name: Category, Length: 1040, dtype: object

In [364]:
data["Food_Item"]=data["Food_Item"].replace("Rice","Risotto")

In [365]:
data["Food_Item"].unique()

array(['Pasta', 'Salad', 'Fries', 'Pizza', 'Sandwich', 'Risotto',
       'Chicken', 'Burger'], dtype=object)

In [366]:
data.loc[data["Food_Item"]=="Fries","Category"]="Fast Food"

In [367]:
data.loc[data["Food_Item"]=="Risotto","Category"]="Italian"

In [368]:
data.loc[data["Food_Item"]=="Pasta","Category"]="Italian"
data.loc[data["Food_Item"]=="Chicken","Category"]="Grill"

In [369]:
data.loc[data["Food_Item"]=="Burger","Category"]="Fast Food"

In [370]:
data.loc[data["Food_Item"]=="Sandwich","Category"]="Fast Food"

In [371]:
data.to_csv("final.csv")